sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    repo: igniterealtime/openfire-pushnotification-plugin
    all_branches: true
env:
  global:
  - secure: bWC+sD7OB1LGTAWzzY5jtsIwnY2H7lvScGPE3YWDVlE/Wbgn+8wDq3o4oNfaKdveoE3FE6IxGTj6Yck8gR3KkxFTNI/2j28GzpNmuml/YnVY1IHfjuqpi+6O7tPBdBd8kZuOJZSyLLvldf1Uw/POlBtguHNuEvgVdHA1AVdk0pGPJnwqAha8H5aue+HN2DkCfgJBKvobI2sIgWg2nbsAZ89kG1rOuhWueIpzw0Lc+ewG3JoaO3J7tzYrQevND3woivhi3LzKythqSFg4RySZLoM+en4Z7z1rwCwu+eqsvuhRFofZtnyTgNtETb3Awyzv2RK7QIz2Bu5O37SpwnF25KCTSyZA9Ub1U3ZSi10ZAJTpzg6KSrTCZHGLJSpaEx1DtFxHtEXvv+dD+srs8TamzmytowoBl+xE0dQropI4e1w1nZPuQfLIrBw7EQ3EXN9VTnyVqd2AZC/ZdfJPPUw4JZWPoXvmCQJNpBVT0nuTkP4vYHJaVaXIwYxKmG8v1FnCUeB7jf8jONEtheB1L+KxPmKkdYDgPuMvSVNN4SUvmHi7DFEHFupQ3rauTgN0OuLoBozC88e2fiVzYfoCo/HAEXnORsoxI0uboESs+mbHCG/bRqm6UOIqsYr/YeQtofc2S4CvR0gW1SmaESW9axTi0dx0wOvBjVctIR082oo5ZOE=
  - secure: LU36Pzot0bqCRtwPSJuQqoeKImo/bjRASbYD2HdrruUNAg8u2MXv42qcfyxXx4WKQmT/xgzuWktEkr6aMO0HQWQtUEGfcJEOHiIVfEyFBFxhPdtlHbgqzc77C56127LVZPJnWwwzxW1y9ULHlo1Y7/D1NjKpsmFfQkLhTPKP0JqR1kyijnnfPZa0bhPuYEsT1PYc78fa8V/o1COjw5trYqgHIGyq0eJoRid5GEefJ32J56u0W8rNUnFP+WjuAe/S1kVqSmOB2mGyxDwHdPWft9O4aGNgZshJv6njWWt2IQL5HBDuuNlSmi3nbtNB6obIcd4Kxd4QNVweRVLa64wJEFE0rPR1OBw9rHSUChb/WTr/LxPDdFjAdDVycBnJ/5GcX5L35YViXBdQa3vtMpNRA7ZgQSYpfLd+puUAOnDWXnLE0xJmGnIAVa7F8V8upycp734SqeaeybjlzmiB5JrMQqi3JkoUkwi0XO7HIyQ7j8+DdoIGyNDVd5vp/Py24n9iXkk6hehn7cMJp8tthfyWjKtgD5ly+8vuNF/7fNf03BrVyXpii8XR4fsFEZG9nWfOKrRi14XH05kfjiHZEuGjyMxDn3SFuQERjDcRnmu1fAd0bLJLHHAG2WfFipa6BFJaGMEBPcr4AfdA4Ze7XZa+vImjnXSApgEJCBwGAX782kI=
